//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

using GameDefine;
using Common.Tools;
using HolyTech.GameData;
//技能中只有声音的特效
namespace HolyTech.Effect
{
    public class OnlySoundEffect : IEffect
    {
        public OnlySoundEffect()
        {
        }
        public override void Update()
        {
            if (isDead)
                return;
                   
            base.Update();
        }
    }
}

